{
 "title": "Terraform Cloud/Enterprise",
 "description": "This Dashboard provides insights about Terraform Cloud/Enterprise resources.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "organizations", "label": "organization", "query": "tf_organizations_info" },
   { "name": "workspace_status", "label": "status", "query": "tf_workspaces_info" }
  ]
 },
 "panels": [
  {
   "title": "Organization Count",
   "type": "stat",
   "description": "Total number of organizations.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(tf_organizations_info{name=~\"$organizations\"})"
    }
   ]
  },
  {
   "title": "Organization Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "tf_organizations_info{name=~\"$organizations\"}"
    }
   ]
  },
  {
   "title": "Workspace Count",
   "type": "stat",
   "description": "Total number of workspaces.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(tf_workspaces_info{organization=~\"$organizations\",current_run_status=~\"$workspace_status\"})"
    }
   ]
  },
  {
   "title": "Workspace Status Overview",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(current_run_status)(tf_workspaces_info{organization=~\"$organizations\",current_run_status=~\"$workspace_status\"})",
     "legendFormat": "{{current_run_status}}"
    }
   ]
  },
  {
   "title": "Workspace Status History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(current_run_status)(tf_workspaces_info{organization=~\"$organizations\",current_run_status=~\"$workspace_status\"})",
     "legendFormat": "{{current_run_status}}"
    }
   ]
  },
  {
   "title": "Workspace Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "tf_workspaces_info{organization=~\"$organizations\",current_run_status=~\"$workspace_status\"}"
    }
   ]
  },
  {
   "title": "Exporter Duration Stats",
   "type": "graph",
   "description": "Time taken by each individual scraper.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "tf_exporter_collector_duration_seconds",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "stat",
   "description": "Result of last API scrape attempt.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tf_exporter_last_scrape_error" }
   ]
  }
 ]
}